name: "Github weather bot"

on:
  schedule:
    - cron: "30 9 * * *"

jobs:
  bot:
    runs-on: ubuntu/latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install node"
        uses: actions/setup-node@v1
      - name: "Install NPM dependencies"
        run: npm i
      - name: "Run code"
        run: node index.js
        env: TELEGRAM_TOKEN = ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID = ${{ secrets.TELEGRAM_CHAT_ID }}
          WEATHER_API_TOKEN = ${{ secrets.WEATHER_API_TOKEN }}
